apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: example-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/containers/imagePullPolicy
        value: IfNotPresent

  - target:
      kind: Job
      name: example-db-migrate
    patch: |-
      - op: replace
        path: /spec/containers/imagePullPolicy
        value: IfNotPresent

  - target:
      kind: ConfigMap
      name: example-api-config
    patch: |-
      - op: replace
        path: /data/SWAGGER_ENABLED
        value: "false"

  - target:
      kind: HorizontalPodAutoscaler
      name: example-api-hpa
    patch: |-
      - op: replace
          path: /spec/minReplicas
          value: 2
      - op: replace
          path: /spec/maxReplicas
          value: 10

  - target:
      kind: Cluster
      name: example-db
    patch: |-
      - op: replace
          path: /spec/instances
          value: 3
