name: Build & push Docker image on Release branches

on:
  push:
    branches:
      - 'Release'
      - 'releases-*.*.*'   # e.g. Release-1.12.3, Release-2.0.0, etc.

env:
  IMAGE_NAME: ${{vars.DOCKERHUB_BYTSER_USERNAME}}/${{vars.DOCKERHUB_IMAGE_NAME}}  # check these vars are correct
  DOCKERHUB_USERNAME: ${{vars.DOCKERHUB_BYTSER_USERNAME}}  # check this var is correct
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_BYTSER_TOKEN_READWRITE }}  # check this secret is set

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Extract version from branch
        id: version
        shell: bash
        run: |
          BRANCH="${GITHUB_REF_NAME}"
          echo "Branch: $BRANCH"

          # If branch is like "Release-1.2.3" use VERSION="1.2.3"
          if [[ "$BRANCH" == releases-* ]]; then
            VERSION="${BRANCH#releases-}"

          # If branch is exactly "Release", use "latest" tag
          elif [[ "$BRANCH" == "Release" ]]; then
            echo "On 'Release' branch, version latest will be used."
            VERSION="latest"

          else
            echo "Unexpected branch name: $BRANCH"
            exit 1
          fi

          echo "Using version: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./docker # Dockerfile is in ./docker
          file: ./docker/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}